/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_opencv_androidstudio_NativeClass */

#ifndef _Included_com_example_ndk_opencv_androidstudio_NativeClass
#define _Included_com_example_ndk_opencv_androidstudio_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_opencv_androidstudio_NativeClass
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndk_1opencv_1androidstudio_NativeClass_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
